# Generated by Django 4.2.4 on 2023-08-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=20)),
                ('scale', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('construction', models.CharField(max_length=50)),
            ],
        ),
    ]
