# Generated by Django 4.2.4 on 2023-08-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('variety', models.CharField(choices=[('R', 'Roundwound'), ('H', 'Halfround'), ('F', 'Flatwould'), ('T', 'Tapewound')], default='R', max_length=1, verbose_name='Type')),
                ('bass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bass')),
            ],
        ),
    ]
