# Generated by Django 4.2.4 on 2023-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_strings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=20)),
                ('wattage', models.IntegerField()),
                ('variety', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='strings',
            name='variety',
            field=models.CharField(choices=[('R', 'Roundwound'), ('H', 'Halfround'), ('F', 'Flatwound'), ('T', 'Tapewound')], default='R', max_length=1, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='bass',
            name='amps',
            field=models.ManyToManyField(to='main_app.amp'),
        ),
    ]
